FROM node:22-alpine AS deps
WORKDIR /app
COPY package*.json ./
COPY api/core/package*.json api/core/
RUN npm install

FROM node:22-alpine AS build
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run prisma:generate
RUN npm run build --workspace @gamad-hub/api-core

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app .
EXPOSE 4000
CMD ["npm", "run", "start", "--workspace", "@gamad-hub/api-core"]
